"""English names for the Japanese spec items used on Panasonic spec sheets.

Items missing here are shown in Japanese only. Group rows are keyed as
"<group> / <item>".
"""

LABELS = {
    "OS": "OS",
    "搭載OS": "OS",
    "CPU": "CPU",
    "チップセット": "Chipset",
    "メインメモリー": "Memory",
    "ビデオメモリー": "Video memory",
    "ストレージ": "Storage",
    "ハードディスクドライブ": "Hard disk",
    "フラッシュメモリードライブ": "SSD",
    "光学式ドライブ": "Optical drive",
    "フロッピーディスクドライブ(オプション)": "Floppy drive (optional)",
    "表示方式": "Display",
    "表示方式 / 表示方式": "Display",
    "表示方式 / グラフィックアクセラレーター": "Display / Graphics",
    "表示方式 / LCD表示": "Display / LCD colors",
    "表示方式 / 外部ディスプレイ出力": "Display / External output",
    "表示方式 / 外部ディスプレイ表示": "Display / External output",
    "表示方式 / 本体＋外部ディスプレイ同時表示": "Display / Simultaneous display",
    "無線LAN": "Wireless LAN",
    "ワイヤレスWAN": "Wireless WAN",
    "LAN": "Wired LAN",
    "モデム": "Modem",
    "Bluetooth": "Bluetooth",
    "サウンド機能": "Audio",
    "セキュリティチップ": "Security chip",
    "セキュリティ(Windows Hello対応)": "Security (Windows Hello)",
    "SDメモリーカードスロット": "SD card slot",
    "カードスロット": "Card slots",
    "カードスロット / SDメモリーカードスロット": "Card slots / SD card",
    "カードスロット / PCカードスロット": "Card slots / PC Card",
    "カードスロット / その他カードスロット": "Card slots / Other",
    "拡張メモリースロット": "Memory expansion slot",
    "カメラ": "Camera",
    "内蔵マイク": "Microphone",
    "センサー": "Sensors",
    "インターフェース": "Ports",
    "キーボード": "Keyboard",
    "ポインティングデバイス": "Pointing device",
    "電源": "Power",
    "消費電力": "Power consumption",
    "エネルギー消費効率": "Energy efficiency",
    "達成率": "Efficiency target achievement",
    "駆動／充電時間": "Battery life / charge time",
    "バッテリー駆動時間": "Battery life",
    "外形寸法(幅×奥行×高さ)": "Dimensions (W×D×H)",
    "本体カラー": "Color",
    "質量(バッテリーを含む）": "Weight (with battery)",
    "ソフトウェア": "Software",
    "Microsoft Office": "Microsoft Office",
    "付属品": "Accessories",
    "その他の付記事項": "Notes",
    "ワイヤレス通信機能": "Wireless communication",
    "連続データ転送速度 / 再生": "Optical drive speed / Read",
    "連続データ転送速度 / 記録": "Optical drive speed / Write",
    "達成率 ( 2011年度基準 )": "Efficiency target achievement (FY2011 standard)",
    "達成率( 2011年度基準 )": "Efficiency target achievement (FY2011 standard)",
    "達成率(2011年度基準)": "Efficiency target achievement (FY2011 standard)",
    "LTE": "LTE",
    "モバイルWiMAX": "Mobile WiMAX",
    "バッテリー": "Battery",
    "対応ディスク、および対応フォーマット / 再生": "Supported discs / Read",
    "対応ディスク、および対応フォーマット / 記録": "Supported discs / Write",
    "対応ディスク・対応フォーマット / 再生": "Supported discs / Read",
    "対応ディスク・対応フォーマット / 記録": "Supported discs / Write",
    "インターフェース / 音声": "Ports / Audio",
    "インターフェース / USBコネクター": "Ports / USB",
    "インターフェース / その他インターフェース": "Ports / Other",
    "インターフェース / 外部ディスプレイコネクター": "Ports / External display",
    "インターフェース / 赤外線通信": "Ports / Infrared",
    "インターフェース / シリアルコネクター": "Ports / Serial",
    "インターフェース / パラレルコネクター": "Ports / Parallel",
    "インターフェース / マウス／外部キーボード": "Ports / Mouse / keyboard",
    "インターフェース / i.LINK端子": "Ports / i.LINK (IEEE 1394)",
    "インターフェース / キーボードベース": "Ports / Keyboard base",
    "インターフェース / タブレット部": "Ports / Tablet",
    "インターフェース / オプション(Ｉ／Ｏボックス)": "Ports / Optional I/O box",
    "インターフェース / オプション（ミニＩ／Ｏボックス）": "Ports / Optional mini I/O box",
    "２次キャッシュメモリー": "L2 cache",
    "コア数": "CPU cores",
    "注意書き": "Notes",
    "お知らせ": "Notice",
    "グラフィックチップ": "Graphics chip",
    "外形寸法（突起部除く）": "Dimensions (excluding protrusions)",
    "PCカードスロット": "PC Card slot",
    "表示方式 / デュアルディスプレイ表示(例)": "Display / Dual display (example)",
    "マルチベイ": "Multi-bay",
    "カードスロット / キーボードベース": "Card slots / Keyboard base",
    "カードスロット / タブレット部": "Card slots / Tablet",
    "ワイヤレスコムポート / 携帯電話": "Wireless com port / Mobile phone",
    "ワイヤレスコムポート / PHS": "Wireless com port / PHS",
    "音声": "Audio port",
    "USBコネクター": "USB",
    "外部ディスプレイコネクター": "External display port",
    "その他インターフェース": "Other ports",
    "オプション(Ｉ／Ｏボックス)": "Optional I/O box",
    "赤外線通信": "Infrared",
    "セキュリティ": "Security",
    "シリアルコネクター": "Serial port",
    "パラレルコネクター": "Parallel port",
    "指紋センサー": "Fingerprint sensor",
}

# Chinese names for the same items.
LABELS_ZH = {
    "OS": "操作系统",
    "搭載OS": "操作系统",
    "CPU": "处理器",
    "チップセット": "芯片组",
    "メインメモリー": "内存",
    "ビデオメモリー": "显存",
    "ストレージ": "存储",
    "ハードディスクドライブ": "硬盘",
    "フラッシュメモリードライブ": "固态硬盘",
    "光学式ドライブ": "光驱",
    "フロッピーディスクドライブ(オプション)": "软驱（选配）",
    "表示方式": "显示屏",
    "表示方式 / 表示方式": "显示屏",
    "表示方式 / グラフィックアクセラレーター": "显示屏 / 显卡",
    "表示方式 / LCD表示": "显示屏 / 色彩",
    "表示方式 / 外部ディスプレイ出力": "显示屏 / 外接显示输出",
    "表示方式 / 外部ディスプレイ表示": "显示屏 / 外接显示输出",
    "表示方式 / 本体＋外部ディスプレイ同時表示": "显示屏 / 同时显示",
    "表示方式 / デュアルディスプレイ表示(例)": "显示屏 / 双屏显示（示例）",
    "無線LAN": "无线网络",
    "ワイヤレスWAN": "无线广域网",
    "ワイヤレス通信機能": "无线通信模块",
    "LAN": "有线网络",
    "LTE": "LTE",
    "モバイルWiMAX": "移动 WiMAX",
    "モデム": "调制解调器",
    "Bluetooth": "蓝牙",
    "サウンド機能": "音频",
    "セキュリティチップ": "安全芯片",
    "セキュリティ(Windows Hello対応)": "安全（Windows Hello）",
    "セキュリティ": "安全",
    "指紋センサー": "指纹传感器",
    "SDメモリーカードスロット": "SD 卡槽",
    "カードスロット": "卡槽",
    "カードスロット / SDメモリーカードスロット": "卡槽 / SD 卡",
    "カードスロット / PCカードスロット": "卡槽 / PC 卡",
    "カードスロット / その他カードスロット": "卡槽 / 其他",
    "カードスロット / キーボードベース": "卡槽 / 键盘底座",
    "カードスロット / タブレット部": "卡槽 / 平板部分",
    "PCカードスロット": "PC 卡槽",
    "拡張メモリースロット": "内存扩展槽",
    "カメラ": "摄像头",
    "内蔵マイク": "麦克风",
    "センサー": "传感器",
    "インターフェース": "接口",
    "インターフェース / 音声": "接口 / 音频",
    "インターフェース / USBコネクター": "接口 / USB",
    "インターフェース / その他インターフェース": "接口 / 其他",
    "インターフェース / 外部ディスプレイコネクター": "接口 / 外接显示",
    "インターフェース / 赤外線通信": "接口 / 红外",
    "インターフェース / シリアルコネクター": "接口 / 串口",
    "インターフェース / パラレルコネクター": "接口 / 并口",
    "インターフェース / マウス／外部キーボード": "接口 / 鼠标 / 键盘",
    "インターフェース / i.LINK端子": "接口 / i.LINK（IEEE 1394）",
    "インターフェース / キーボードベース": "接口 / 键盘底座",
    "インターフェース / タブレット部": "接口 / 平板部分",
    "インターフェース / オプション(Ｉ／Ｏボックス)": "接口 / 选配 I/O 盒",
    "インターフェース / オプション（ミニＩ／Ｏボックス）": "接口 / 选配迷你 I/O 盒",
    "音声": "音频接口",
    "USBコネクター": "USB",
    "外部ディスプレイコネクター": "外接显示接口",
    "その他インターフェース": "其他接口",
    "オプション(Ｉ／Ｏボックス)": "选配 I/O 盒",
    "赤外線通信": "红外",
    "シリアルコネクター": "串口",
    "パラレルコネクター": "并口",
    "キーボード": "键盘",
    "ポインティングデバイス": "指点设备",
    "電源": "电源",
    "消費電力": "功耗",
    "エネルギー消費効率": "能效",
    "達成率": "能效达成率",
    "達成率 ( 2011年度基準 )": "能效达成率（2011 年度标准）",
    "達成率( 2011年度基準 )": "能效达成率（2011 年度标准）",
    "達成率(2011年度基準)": "能效达成率（2011 年度标准）",
    "駆動／充電時間": "续航 / 充电时间",
    "バッテリー駆動時間": "续航时间",
    "バッテリー": "电池",
    "外形寸法(幅×奥行×高さ)": "尺寸（宽×深×高）",
    "外形寸法（突起部除く）": "尺寸（不含凸起部分）",
    "本体カラー": "颜色",
    "質量(バッテリーを含む）": "重量（含电池）",
    "ソフトウェア": "预装软件",
    "Microsoft Office": "Microsoft Office",
    "付属品": "附件",
    "その他の付記事項": "备注",
    "注意書き": "注意事项",
    "お知らせ": "通知",
    "２次キャッシュメモリー": "二级缓存",
    "コア数": "核心数",
    "グラフィックチップ": "显示芯片",
    "マルチベイ": "多功能仓位",
    "ワイヤレスコムポート / 携帯電話": "无线通信端口 / 手机",
    "ワイヤレスコムポート / PHS": "无线通信端口 / PHS",
    "連続データ転送速度 / 再生": "光驱速度 / 读取",
    "連続データ転送速度 / 記録": "光驱速度 / 写入",
    "対応ディスク、および対応フォーマット / 再生": "支持光盘 / 读取",
    "対応ディスク、および対応フォーマット / 記録": "支持光盘 / 写入",
    "対応ディスク・対応フォーマット / 再生": "支持光盘 / 读取",
    "対応ディスク・対応フォーマット / 記録": "支持光盘 / 写入",
}
